---
title: "how_to_set_twitter_time_and_distance"
author: "Kristin Robinson"
date: "April 29, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(lubridate)
library(ggplot2)
library(dplyr)
library(readr)

# library for calculating distance between two coords in degrees
library(geosphere)

options(stringsAsFactors = FALSE)

```

```{r}
twitter_data <- read.csv("data/twitter/twitter_31days_OLD.csv")
twitter_backup <- twitter_data
```


```{r formt-twitter-data}
## format time ##
# load data - longitude and latitude already transformed)
twitter_data$Timestamp<-as.POSIXct(twitter_data$Timestamp)
# twitter_data <- subset(twitter_data, 
#                            twitter_data$Timestamp >= ('2014-04-24 04:20:44') &
#                            twitter_data$Timestamp <= ('2014-09-24 04:29:59') )

## manipulate long & lat into usable form ##
# split coordinates into two columns and remove special characters
twitter_data$lon <- sapply(strsplit(as.character(twitter_data$Coordinates),','), "[", 1) 
twitter_data$lon <- (sub('^\\[', '', twitter_data$lon)) %>% as.numeric(twitter_data$lon)
twitter_data$lat <- sapply(strsplit(as.character(twitter_data$Coordinates),','), "[", 2)
twitter_data$lat <- (sub(']$', '', twitter_data$lat))

# cast strings as num
twitter_data$lon <-as.numeric(twitter_data$lon)
twitter_data$lat <-as.numeric(twitter_data$lat)

# set column to epicenter lon and one col to epicenter lat (-122.31, 38.22)
twitter_data$epicenlon <- as.numeric(-122.31)
twitter_data$epicenlat <- as.numeric(38.22)

# meters in a mile
m_per_mi <- 1609.34

# distance from epicenter test
# dist <- (distVincentySphere(c(-122.319200, 38.21420),c(-122.31, 38.22)))/m_per_mi

# cal distance from epicenter
twitter_data <- twitter_data %>% mutate(dist = distHaversine(cbind(lon, lat), cbind(epicenlon, epicenlat)))
twitter_data$dist <- twitter_data$dist/m_per_mi


```


```{r add-time-spans}
# set eruption date and time
day1 <- as.Date("2014-08-24")
hour1 <- as.POSIXct("2014-08-24 04:20:44")

# add columns for elapsed days, mins, secs
twitter_data$frac_day_from_erup <- as.numeric(difftime(twitter_data$Timestamp, hour1, units = "days"))
twitter_data$whole_day_from_erup <- as.numeric(difftime (as.Date(twitter_data$Timestamp), day1, units = "days"))
twitter_data$frac_min_from_erup <- as.numeric(difftime(twitter_data$Timestamp, hour1, units = "mins"))
twitter_data$whole_min_from_erup <-trunc(twitter_data$frac_min_from_erup, "mins")
twitter_data$sec_from_erup <- as.numeric(difftime(twitter_data$Timestamp, hour1, units = "secs"))

# write.csv(twitter_data, "data/twitter_data_31day.csv")
```
