---
title: "Twitter_and_shakemap_plots"
author: "Kristin Robinson"
date: "April 18, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

# load libraries
library(tidyverse)
library(stringr)
library(dplyr)
library(readr)
library(chunked)
library(ff)
library(maps)
library(ggmap)
library(lubridate)
library(gsheet)
library(ggplot2)
library(viridis)

options(stringsAsFactors = FALSE)
```

Napa earthquake August 24, 2014 10:20:44 UTC
epicenter: 38.22?N 122.31?W
https://en.wikipedia.org/wiki/2014_South_Napa_earthquake


```{r shake-data}

shakemap_data <- read.csv("data/shakemap/shakemap.csv", header=TRUE)
shakemap_data <- na.omit(shakemap_data)

```

```{r twitter-data}
# load data - longitude and latitude already transformed
# twitter_data_10min <- read.csv("data/twitter/twitter_data_10min.csv")
twitter_data_31day <- read.csv("data/twitter/twitter_data_31day.csv")
twitter_data_31day$Timestamp<-as.POSIXct(twitter_data_31day$Timestamp)
twitter_data_1day <- subset(twitter_data_31day, 
                             twitter_data_31day$Timestamp >= ('2014-08-24 04:20:44') &
                            twitter_data_31day$Timestamp <= ('2014-08-25 04:20:43') )

```

```{r plot-tweets-per-day}
# plot no. of tweets in 1 day intervals
# twitter_data_1day$hour_from_erup <- (twitter_data_1day$whole_min_from_erup)/60

ggplot(twitter_data_31day, aes(whole_day_from_erup)) +
  #geom_histogram(binwidth = 1, boundary = 1, closed = "left") +
  geom_histogram(breaks=seq(0, 31, by = 1),
                 col = "black",
                 fill = "blue",
                 alpha = .2)+
  labs(x = "Tweets per day", 
       y = "Number of tweets", 
       title = "Days from eruption") +
  xlim(c(0,31))

ggplot(twitter_data_1day, aes(hour_from_erup)) +
  geom_histogram(breaks=seq(0, 23, by = 1),
                 col = "black",
                 fill = "blue",
                 alpha = .2)+
  labs(x = "Hours from eruption", 
       y = "Number of tweets", 
       title = "Tweets per hour") +
  xlim(c(0,23))
```

```{r plot-tweets-per-day}
# plot no. of tweets in day intervals
ggplot(twitter_data_31day, aes(whole_day_from_erup)) +
  geom_freqpoly() +
  labs(x = "Time (CDT)",
       y = "Number of tweets",
       title = "Tweets over days")


```


```{r hist-tweets-over-time-mins}
# add column of time: minutes from eq
# twitter_data_10min$minutes <- minute(twitter_data_10min$Timestamp)-20

# plot no. of tweets in 1 min intervals
ggplot(twitter_data_10min, aes(whole_min_from_erup)) +
  geom_histogram() +
  labs(x = "Minutes after earthquake", y = "Number of tweets", title = "Number of tweets over time (minute intervals)")

ggplot(twitter_data_10min, aes(whole_min_from_erup)) +
  #geom_histogram(binwidth = 1, boundary = 1, closed = "left") +
  geom_histogram(breaks=seq(0, 9, by = 1),
                 col = "black",
                 fill = "blue",
                 alpha = .2)+
  labs(x = "Minutes after earthquake", 
       y = "Number of tweets", 
       title = "Minutes from eruption") +
  xlim(c(0,9))
```
```{r}
library(grid)
library(gridExtra)

hist_31day <-ggplot(twitter_data_31day, aes(whole_day_from_erup)) +
  #geom_histogram(binwidth = 1, boundary = 1, closed = "left") +
  geom_histogram(breaks=seq(0, 31, by = 1),
                 col = "black",
                 fill = "blue",
                 alpha = .2)+
  labs(x = "Tweets per day", 
       y = "Number of tweets", 
       title = "31 days") +
  xlim(c(0,31))

hist_1day <-ggplot(twitter_data_1day, aes(hour_from_erup)) +
  geom_histogram(breaks=seq(0, 23, by = 1),
                 col = "black",
                 fill = "green",
                 alpha = .2)+
  labs(x = "Hours from eruption", 
       y = "Number of tweets", 
       title = "24 hours") +
  xlim(c(0,23))

hist_1min <- ggplot(twitter_data_10min, aes(whole_min_from_erup)) +
  #geom_histogram(binwidth = 1, boundary = 1, closed = "left") +
  geom_histogram(breaks=seq(0, 9, by = 1),
                 col = "black",
                 fill = "darkred",
                 alpha = .2)+
  labs(x = "Minutes after earthquake", 
       y = "Number of tweets", 
       title = "10 minutes") +
  xlim(c(0,9))


grid.arrange(hist_31day, hist_1day, hist_1min, ncol = 3, top = "Tweets by time from eruption\nSouth Napa Earthquake")

```

```{r plot-distance-from-epicenter}

# plot number of tweets by distance from epicenter
ggplot(twitter_data_10min, aes(dist)) +
  geom_freqpoly(binwidth = 1) +
  labs(x = "miles from epicenter", 
       title = "# of Tweets by Distance from Epicenter")

# plot number of tweets by time by distance
dist_all <- ggplot(twitter_data_10min, 
       aes(x = frac_min_from_erup, 
           y = dist)) +
  geom_point(colour = "royalblue2", size = 1) + 
  scale_x_continuous("minutes after eruption", 
                     breaks = c(0,1,2,3,4,5,6,7,8,9)) + 
   scale_y_continuous("distance (mi)") + 
  labs(subtitle = "distance: global")


# plot number of tweets by time by distance (distance <= 500 miles)
dist_500mi <- ggplot(twitter_data_10min, 
                     aes(x = frac_min_from_erup, 
                         y = dist)) + 
  geom_point(colour = "royalblue2", size = 1) +
  scale_x_continuous("minutes after eruption", 
                     breaks = c(0,1,2,3,4,5,6,7,8,9)) + 
  scale_y_continuous("distance (mi)", limits = c(0,500)) +
  labs(subtitle = "distance: 0 - 500 mi." )
 

# plot number of tweets by time by distance (distance <= 100 miles)
dist_100mi <- ggplot(twitter_data_10min, 
                     aes(x = frac_min_from_erup,
                         y = dist)) + 
  geom_point(colour = "royalblue2", size = 1) +
  scale_x_continuous("minutes after eruption", 
                     breaks = c(0,1,2,3,4,5,6,7,8,9)) + 
  scale_y_continuous("distance (mi)", limits = c(0,100)) +
  labs(subtitle = "distance: 0 - 100 mi." )

# plot number of tweets by time by distance (distance <= 50 mi.)
dist_50mi <- ggplot(twitter_data_10min, 
                    aes(x = frac_min_from_erup, 
                        y = dist)) + 
  geom_point(colour = "royalblue2", size = 1) +
  scale_x_continuous("minutes after eruption", 
                     breaks = c(0,1,2,3,4,5,6,7,8,9)) + 
  scale_y_continuous("distance (mi)", limits = c(0,50)) +
  labs(subtitle = "distance: 0 - 50 mi." )


grid.arrange(dist_all, dist_500mi, dist_100mi, dist_50mi, ncol = 2, 
             top = "Tweets by Distance\nSouth Napa Earthquake")
```




```{r map-tweets}
# get california map
napa_map <- get_map(location = "napa, ca", 
                     source = "google",
                     maptype = "terrain", 
                     crop = FALSE,
                     zoom = 9)

# plot twitter data
ggmap(napa_map) +
  geom_point(data = twitter_data_10min, 
             col = "red", 
             size = .1,
             aes(x = lon, 
                 y = lat),
             shape = 19) +
  guides(fill = FALSE, 
         alpha = FALSE, 
         size = FALSE)

```

```{r}

# plot shakemap intensity
ggmap(napa_map) +
  geom_point(data=shakemap_data, aes(x=longitude, y= latitude, color = intensity), alpha = 1) + scale_color_continuous(low = "yellow", high = "red")

  
```


```{r}

# plot twitter & shake intensity data
ggmap(napa_map) +
  geom_point(data=shakemap_data, aes(x=longitude, y= latitude, color = intensity), alpha = 1) + scale_color_continuous(low = "yellow", high = "red")+
  geom_point(data = twitter_data_10min, 
             col = "green", 
             size = .1,
             aes(x = lon, 
                 y = lat),
             shape = 19)
```