---
title: "Presentation Plots"
author: "Kristin Robinson"
date: "May 2, 2017"
output: html_document
---

```{r setup, include=FALSE}
# work with spatial data; sp package will load with rgdal.
library(rgdal)
library(rgeos)
# for metadata/attributes- vectors or rasters
library(raster)

library(ggplot2)
# testing the sf package out for these lessons!
# library(sf)
library(RColorBrewer)

library(maps)
library(ggmap)
library(dplyr)

library(devtools)
library(leaflet)


options(stringsAsFactors = FALSE)
```

8/23/2012-3/14/2017	735,637	 1,048,576 
2014	201,430	 610,955 
31 days	25,267	67,593
1 day	4944	15309
10 min	2,457	867


```{r shakemap-data}
# load data
shakemap_data <- read.csv("data/shakemap/shakemap.csv", header=TRUE)
shakemap_data <- na.omit(shakemap_data)

# load shapefile
shake_sh <- readOGR(dsn="data/shakemap/shapefile/mi.shp")
shake_sh$GRID_CODE<-as.numeric(shake_sh$GRID_CODE)

# load raster
shake_rs <- raster("data/shakemap/raster/mi.fit")

```
 
 Epicenter -123.56, 37.38, -121.05, 39.05

```{r shakemap}

library(sp)
napa_map <- get_map(location = "Napa, California",
               source = "google",
               maptype = "terrain",
               crop = TRUE,
               zoom = 8)



aoi <- as(raster::extent(shake_sh), "SpatialPolygons")
proj4string(aoi) <- "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs"

  

m <- ggmap(napa_map, extent = "device") + 
  geom_polygon(aes(x = long, 
                   y = lat, 
                   group=id),
               data = aoi, 
               color = "blue", 
               fill = NA,
               alpha = 1, 
               size = 1)  + 
  geom_point(
    aes(x = -122.31, 
        y = 38.22),
    colour = "red",
    size = 6,
    shape = 19) +
  geom_text(aes(x = -122.31, 
        y = 38.22, label = "Epicenter"), colour = "red", size = 8, hjust = -.2, vjust =.2)
#m +labs(title = "ShakeMap boundary\n 2014 South Napa Earthquake") + 
#  theme(legend.position="none")
  
m + ggtitle("2014 South Napa Earthquake\nShakeMap boundary") +
  theme(plot.title = element_text(family = "Times", color="#666666", face="bold", size=32, hjust=0)) +
  theme(legend.position="none")
  
# theme(legend.title=element_blank())+ scale_colour_discrete(
#                         labels=c("Epicenter"))

```



```{r shake-leaflet-shape}

# create epicenter icon
epi <- makeIcon(
  iconUrl = "http://icons.iconarchive.com/icons/icons-land/vista-map-markers/256/Map-Marker-Ball-Pink-icon.png",
  iconWidth = 60, iconHeight = 60,
  iconAnchorX = 0, iconAnchorY = 0)

# set colors for ShakeMap palette
cols <- c("#FFFFFF","#FFFFFF", "#BFCCFF", "#A0E6FF", "#80FFFF", "#7AFF93", "#FFFF00", "#FFC800","#FF9100","#C80000")

# create palette
pal1 <- colorNumeric(palette = cols, domain = shake_sh$PARAMVALUE)
pal2 <- colorNumeric(palette = cols, domain = shake_sh$GRID_CODE)

# plot 
leaflet(shake_sh) %>% addProviderTiles(providers$OpenMapSurfer.Roads, group = "Base map") %>% fitBounds(-123.56, 37.38, -121.05, 39.05) %>%
  addPolygons(color = ~pal2(GRID_CODE), 
              weight = 1, 
              smoothFactor = 0.5,
              opacity = .5, 
              fillOpacity = 0.6, 
              fillColor = ~pal1(PARAMVALUE),
              group = "ShakeMap")%>%
  addMarkers(lng = -122.31, lat = 38.22, group = "Epicenter") %>%
  addLegend(pal = pal2, values = ~GRID_CODE, position = "bottomright",
    title = "Intensity") %>%
  addLayersControl(
    baseGroups = ("Base map"),
    overlayGroups= c("ShakeMap", "Epicenter"),
    options = layersControlOptions(collapsed = FALSE)
  )
```



```{r shake-leaflet-raster}

crs(shake_rs) <- sp::CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")
pal3 <- colorNumeric((palette = cols), values(shake_rs))

leaflet() %>% addTiles() %>%
  addRasterImage(shake_rs, colors = pal3, opacity = 0.6) %>%
  addMarkers(lng = -122.31, lat = 38.22) %>%
  addLegend(pal = pal3, values = values(shake_rs),
    title = "Intesity")

```


```{r twitter-data}
# load data

twitter_data_10min <- read.csv("data/twitter/twitter_data_10min.csv")
twitter_data_31day <- read.csv("data/twitter/twitter_data_31day.csv")
twitter_data_31day$Timestamp<-as.POSIXct(twitter_data_31day$Timestamp)
twitter_data_1day <- subset(twitter_data_31day, 
                             twitter_data_31day$Timestamp >= ('2014-08-24 04:20:44') &
                            twitter_data_31day$Timestamp <= ('2014-08-25 04:20:43') )
```

```{r tweeet-by-time-grid}

library(grid)
library(gridExtra)

hist_31day <-ggplot(twitter_data_31day, aes(whole_day_from_erup)) +
  #geom_histogram(binwidth = 1, boundary = 1, closed = "left") +
  geom_histogram(breaks=seq(0, 31, by = 1),
                 col = "black",
                 fill = "blue",
                 alpha = .2)+
  labs(x = "Tweets per day", 
       y = "Number of tweets", 
       title = "31 days") +
  xlim(c(0,31))

hist_1day <-ggplot(twitter_data_1day, aes(hour_from_erup)) +
  geom_histogram(breaks=seq(0, 23, by = 1),
                 col = "black",
                 fill = "green",
                 alpha = .2)+
  labs(x = "Hours from eruption", 
       y = "Number of tweets", 
       title = "24 hours") +
  xlim(c(0,23))

hist_1min <- ggplot(twitter_data_10min, aes(whole_min_from_erup)) +
  #geom_histogram(binwidth = 1, boundary = 1, closed = "left") +
  geom_histogram(breaks=seq(0, 9, by = 1),
                 col = "black",
                 fill = "darkred",
                 alpha = .2)+
  labs(x = "Minutes after earthquake", 
       y = "Number of tweets", 
       title = "10 minutes") +
  xlim(c(0,9))


grid.arrange(hist_31day, hist_1day, hist_1min, ncol = 3, top = "Tweets by time from eruption\nSouth Napa Earthquake")

```

```{r tweets-by-distance}
# plot number of tweets by time by distance
dist_all <- ggplot(twitter_data_10min, 
       aes(x = frac_min_from_erup, 
           y = dist)) +
  geom_point(colour = "royalblue2", size = 1) + 
  scale_x_continuous("minutes after eruption", 
                     breaks = c(0,1,2,3,4,5,6,7,8,9)) + 
   scale_y_continuous("distance (mi)") + 
  labs(subtitle = "distance: global")


# plot number of tweets by time by distance (distance <= 500 miles)
dist_500mi <- ggplot(twitter_data_10min, 
                     aes(x = frac_min_from_erup, 
                         y = dist)) + 
  geom_point(colour = "royalblue2", size = 1) +
  scale_x_continuous("minutes after eruption", 
                     breaks = c(0,1,2,3,4,5,6,7,8,9)) + 
  scale_y_continuous("distance (mi)", limits = c(0,500)) +
  labs(subtitle = "distance: 0 - 500 mi." )
 

# plot number of tweets by time by distance (distance <= 100 miles)
dist_100mi <- ggplot(twitter_data_10min, 
                     aes(x = frac_min_from_erup,
                         y = dist)) + 
  geom_point(colour = "royalblue2", size = 1) +
  scale_x_continuous("minutes after eruption", 
                     breaks = c(0,1,2,3,4,5,6,7,8,9)) + 
  scale_y_continuous("distance (mi)", limits = c(0,100)) +
  labs(subtitle = "distance: 0 - 100 mi." )

# plot number of tweets by time by distance (distance <= 50 mi.)
dist_50mi <- ggplot(twitter_data_10min, 
                    aes(x = frac_min_from_erup, 
                        y = dist)) + 
  geom_point(colour = "royalblue2", size = 1) +
  scale_x_continuous("minutes after eruption", 
                     breaks = c(0,1,2,3,4,5,6,7,8,9)) + 
  scale_y_continuous("distance (mi)", limits = c(0,50)) +
  labs(subtitle = "distance: 0 - 50 mi." )


grid.arrange(dist_all, dist_500mi, dist_100mi, dist_50mi, ncol = 2, 
             top = "Tweets by Distance\nSouth Napa Earthquake")
```
