---
title: "shakemap"
author: "Kristin Robinson"
date: "May 1, 2017"
output: html_document
---

```{r setup, include=FALSE}
# work with spatial data; sp package will load with rgdal.
library(rgdal)
library(rgeos)
# for metadata/attributes- vectors or rasters
library(raster)

library(ggplot2)
# testing the sf package out for these lessons!
# library(sf)
library(RColorBrewer)

library(maps)
library(ggmap)
library(dplyr)

library(devtools)
library(leaflet)


options(stringsAsFactors = FALSE)
```

```{r}
shakemap_data <- read.csv("data/shakemap/shakemap.csv", header=TRUE)
shakemap_data <- na.omit(shakemap_data)
```


```{r cars}
# Import a polygon shapefile

shake_sh <- readOGR(dsn="data/shakemap/shapefile/mi.shp")
shake_rs <- raster("data/shakemap/raster/mi.fit")
shake_sh$GRID_CODE<-as.numeric(shake_sh$GRID_CODE)

plot(shake_sh, col=shake_sh$PARAMVALUE,
     main = "South Napa Earthquake Shakemap")

pal <- colorNumeric(palette = "Spectral", reverse = TRUE, domain = shake_sh$PARAMVALUE)
pal2 <- colorNumeric(palette = ("Spectral"), reverse = TRUE, domain = shake_sh$GRID_CODE)

leaflet(shake_sh) %>% addProviderTiles(providers$OpenMapSurfer.Roads) %>%
  addPolygons(color = ~pal(GRID_CODE), 
              weight = .6, 
              smoothFactor = 0.5,
              opacity = .5, 
              fillOpacity = 0.5, 
              fillColor = ~pal(PARAMVALUE))


# create a data.frame with the epicenter location
epicenter <- data.frame(lon=c(-122.31),
                lat=c(38.22))


# turn the axis color to white and turn off ticks
# par(col.axis="white", col.lab="white", tck=0)

#plot(shake_rs,
#     main = "Napa Earthquake MMI")
#  plot(shake_sh,
#     add = TRUE) +
# turn the box to white so there is no border on our plot
# box(col="white")


# map_extent <- spTransform(base_map, CRS = crs(shake_rs))


# add a point to the map
ggmap(napa_map) +
                geom_point(
                aes(x=-122.31, y=38.22, group=NULL), colour = "springgreen",
                      size=5)


```
class       : SpatialPolygonsDataFrame 
features    : 768 
extent      : -123.5623, -121.0623, 37.38187, 39.04853  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0 
variables   : 6
names       : AREA, PERIMETER, PGAPOL_, PGAPOL_ID, GRID_CODE, PARAMVALUE 
min values  :    0,         0,      10,         1,         1,        1.7 
max values  :    0,         0,      99,        99,         8,        8.3 

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
