---
title: "Twitter_tests"
author: "Kristin Robinson"
date: "April 18, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

# load libraries
library(tidyverse)
library(stringr)
library(dplyr)
library(readr)
library(chunked)
library(ff)
library(maps)
library(ggmap)
library(lubridate)
library(gsheet)
library(ggplot2)
library(viridis)

options(stringsAsFactors = FALSE)
```

Napa earthquake August 24, 2014 10:20:44 UTC
epicenter: 38.22?N 122.31?W
https://en.wikipedia.org/wiki/2014_South_Napa_earthquake


```{r shake-data}

shake_station_data <- read.csv("data/shakemap/stationlist2.csv", header=TRUE)
shake_station_data <- na.omit(shake_station_data)

```

```{r twitter-data}
# load data - longitude and latitude already transformed
twitter_data_10min <- read.csv("data/twitter/twitter_20140824.csv")
twitter_data_10min$Timestamp<-as.POSIXct(twitter_data_10min$Timestamp)
twitter_data_10min <- subset(twitter_data_10min, twitter_data_10min$Timestamp >= ('2014-08-24 04:20:00') &
                            twitter_data_10min$Timestamp <= ('2014-08-24 04:29:59') )

## gsheet not working ##
#twitter <- gsheet2tbl("https://docs.google.com/spreadsheets/d/18Tf9_ieboON_U4tKylJ8drS5H2Xzm9ka17hoiDIdz24/edit?usp=sharing")
#twitter$Timestamp<-as.POSIXct(twitter$Timestamp)

```

```{r plot-tweets-per-10-sec}
# plot no. of tweets in 10 sec intervals
ggplot(twitter_data_10min, aes(Timestamp)) +
  geom_freqpoly(binwidth = 10) +
  labs(x = "Time (CDT)", y = "Number of tweets", title = "Tweets over time (10 second intervals)")
# could also use + geom_histogram
```

```{r hist-tweets-over-time-mins}
# add column of time: minutes from eq
twitter_data_10min$minutes <- minute(twitter_data_10min$Timestamp)-20

# plot no. of tweets in 1 min intervals
ggplot(twitter_data_10min, aes(minutes)) +
  geom_histogram() +
  labs(x = "Minutes after earthquake", y = "Number of tweets", title = "Number of tweets over time (minute intervals)")
```

```{r plot-tweets-distance-from-epi-over-time}
# library for calculating distance between two coords in degrees
library(geosphere)

# set column to epicenter lon and one col to epicenter lat (-122.31, 38.22)
twitter_data_10min$epicenlon <- as.numeric(-122.31)
twitter_data_10min$epicenlat <- as.numeric(38.22)

# meters in a mile
m_per_mi <- 1609.34

# distance from epicenter test
# dist <- (distVincentySphere(c(-122.319200, 38.21420),c(-122.31, 38.22)))/m_per_mi

# cal distance from epicenter
twitter_data_10min <- twitter_data_10min %>% mutate(dist = distHaversine(cbind(lon, lat), cbind(epicenlon, epicenlat)))
twitter_data_10min$dist <- twitter_data_10min$dist/m_per_mi

# plot number of tweets by distance from epicenter
ggplot(twitter_data_10min, aes(dist)) +
  geom_freqpoly(binwidth = 1) +
  labs(x = "miles from epicenter", title = "# of Tweets by Distance from Epicenter")

# plot number of tweets by time by distance (distance <= 500 miles)
ggplot(twitter_data_10min, aes(x = Timestamp, y = dist)) + geom_point() +ylim(0,100) + labs(title="Tweets by distance by time\n(distance < 500 miles)", x = "time", y="distance (miles)")




```




```{r map-tweets}
# get california map
cal_map <- get_map(location = "napa, ca", 
                     source = "google",
                     maptype = "terrain", 
                     crop = FALSE,
                     zoom = 9)

# plot twitter data
ggmap(cal_map) +
  geom_point(data = twitter_data_10min, 
             col = "red", 
             size = .1,
             aes(x = lon, 
                 y = lat),
             shape = 19) +
  guides(fill = FALSE, 
         alpha = FALSE, 
         size = FALSE)

```

```{r}

# plot shakemap intensity
ggmap(cal_map) +
  geom_point(data=shake_station_data, aes(x=longitude, y= latitude, color = intensity), alpha = 1) + scale_color_continuous(low = "yellow", high = "red")

  
```


```{r}

# plot twitter & shake intensity data
ggmap(cal_map) +
  geom_point(data=shake_station_data, aes(x=longitude, y= latitude, color = intensity), alpha = 1) + scale_color_continuous(low = "yellow", high = "red")+
  geom_point(data = twitter_data_10min, 
             col = "green", 
             size = .1,
             aes(x = lon, 
                 y = lat),
             shape = 19)
```